#!/bin/bash -l 
#SBATCH --cluster=genius 
#SBATCH --job-name phasing 
#SBATCH --nodes=1 
#SBATCH --cpus-per-task=20
#SBATCH --time=24:00:00 
#SBATCH -A lp_svbelleghem
#SBATCH -o phasing.%j.out

# Load java to use beagle
module load Java/11.0.20

module load BCFtools/1.9-foss-2018a

# take only region of interest for phasing
bcftools view -r CHR3:34874684-34909607 P_chalceus_NP25_BarSW_merged_filtered_mm80_multiSplit.vcf.gz -Oz -o P_chalceus_NP25_BarSW_merged_filtered_mm80_multiSplit_chr3_regionMRWS.vcf.gz

# Index new vcf
tabix -p vcf P_chalceus_NP25_BarSW_merged_filtered_mm80_multiSplit_chr3_regionWL.vcf.gz

# Phasing with beagle, no imputing
java -Xmx20g -jar /data/leuven/361/vsc36175/beagle.27Feb25.75f.jar \
  gt=P_chalceus_NP25_BarSW_merged_filtered_mm80_multiSplit_chr3_regionWL.vcf.gz \
  out=P_chalceus_NP25_BarSW_merged_filtered_mm80_multiSplit_chr3_regionWL_phased \
  nthreads=16 \
  impute=false

tabix -p vcf P_chalceus_NP25_BarSW_merged_filtered_mm80_multiSplit_chr3_regionWL_phased.vcf.gz
